### ISSUE TITLE
2.3 系统 Crash

### ISSUE THREAD

**Issue by imesong** [moduth/blockcanary#15]
在2.3系统上，会发生crash ，日志如下

```
AndroidRuntime﹕ FATAL EXCEPTION: BlockCanaryThread_writelog
    java.lang.IllegalArgumentException: contentView required: pkg=***id=-558907665 notification=Notification(vibrate=null,sound=null,defaults=0x0,flags=0x10)
            at android.os.Parcel.readException(Parcel.java:1326)
            at android.os.Parcel.readException(Parcel.java:1276)
            at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:274)
            at android.app.NotificationManager.notify(NotificationManager.java:111)
            at android.app.NotificationManager.notify(NotificationManager.java:91)
            at com.github.moduth.blockcanary.BlockCanary.notify(BlockCanary.java:194)
            at com.github.moduth.blockcanary.BlockCanary.access$200(BlockCanary.java:29)
            at com.github.moduth.blockcanary.BlockCanary$1.onBlockEvent(BlockCanary.java:67)
            at com.github.moduth.blockcanary.LooperPrinter$1.run(LooperPrinter.java:57)
            at android.os.Handler.handleCallback(Handler.java:587)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:130)
            at android.os.HandlerThread.run(HandlerThread.java:60)


```

**Comment by markzhai** [comment]
看上去是创建notification的时候crash的，有没有更详细的log呢

**Comment by imesong** [comment]
这个应该就是比较详细的日志了，每次必先的。我又用demo 工程跑了一下，具体日志如下

```
03-04 04:27:10.680 31522-31537/com.example.blockcanary E/AndroidRuntime: FATAL EXCEPTION: BlockCanaryThread_writelog
                                                                         java.lang.IllegalArgumentException: contentView required: pkg=com.example.blockcanary id=-558907665 notification=Notification(vibrate=null,sound=null,defaults=0x0,flags=0x10)
                                                                             at android.os.Parcel.readException(Parcel.java:1326)
                                                                             at android.os.Parcel.readException(Parcel.java:1276)
                                                                             at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:274)
                                                                             at android.app.NotificationManager.notify(NotificationManager.java:111)
                                                                             at android.app.NotificationManager.notify(NotificationManager.java:91)
                                                                             at com.github.moduth.blockcanary.BlockCanary.notify(BlockCanary.java:194)
                                                                             at com.github.moduth.blockcanary.BlockCanary.access$200(BlockCanary.java:29)
                                                                             at com.github.moduth.blockcanary.BlockCanary$1.onBlockEvent(BlockCanary.java:67)
                                                                             at com.github.moduth.blockcanary.LooperPrinter$1.run(LooperPrinter.java:57)
                                                                             at android.os.Handler.handleCallback(Handler.java:587)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                             at android.os.Looper.loop(Looper.java:130)
                                                                             at android.os.HandlerThread.run(HandlerThread.java:60)
```
