### ISSUE TITLE
在没有开启BlockCanary的时候，启动DisplayBlockActivity会crash

### ISSUE THREAD

**Issue by XiaolongJason** [moduth/blockcanary#31]
没有开启的时候，BlockCanaryCore.getContext()返回是null，导致崩溃，崩溃堆栈如下：
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.github.moduth.blockcanary.IBlockCanaryContext.getLogPath()' on a null object reference
                                                                                   at com.github.moduth.blockcanary.log.BlockCanaryInternals.getPath(BlockCanaryInternals.java:30)
                                                                                   at com.github.moduth.blockcanary.log.BlockCanaryInternals.detectedLeakDirectory(BlockCanaryInternals.java:38)
                                                                                   at com.github.moduth.blockcanary.log.BlockCanaryInternals.getLogFiles(BlockCanaryInternals.java:46)
                                                                                   at com.github.moduth.blockcanary.ui.DisplayBlockActivity$LoadBlocks.run(DisplayBlockActivity.java:395)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                   at java.lang.Thread.run(Thread.java:818)

**Comment by markzhai** [comment]
@XiaolongJason 为什么会在没有开启BlockCanary的时候，启动DisplayBlockActivity呢？没有开启的话，应该是进不去的。是之前装过开启的版本？

**Comment by XiaolongJason** [comment]
@markzhai 在没有调用BlockCanary.install(this, new AppBlockCanaryContext()).start();的情况下，如果引入 'com.github.moduth:blockcanary-ui:1.1.4'，安装完之后桌面会生成Blocks的图标，点击就会出现这个crash。
