### ISSUE TITLE
Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by qq137712630** [moduth/blockcanary#44]
新安装后，点击通知时报了这个，已初次化：  
    
    04-13 22:28:18.183 8079-8079/com.ms.meizinewsapplication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ms.meizinewsapplication, PID: 8079
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at com.github.moduth.blockcanary.ui.DisplayBlockActivity.getBlock(DisplayBlockActivity.java:313)
       at com.github.moduth.blockcanary.ui.DisplayBlockActivity.updateUi(DisplayBlockActivity.java:218)
       at com.github.moduth.blockcanary.ui.DisplayBlockActivity.access$400(DisplayBlockActivity.java:65)
       at com.github.moduth.blockcanary.ui.DisplayBlockActivity$LoadBlocks$2.run(DisplayBlockActivity.java:420)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5691)
       at java.lang.reflect.Method.invoke(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
       
---------------------------------------------------------------------------------------------

    public class AppBlockCanaryContext extends BlockCanaryContext {
        private static final String TAG = "AppBlockCanaryContext";

        /**
         * 标示符，可以唯一标示该安装版本号，如版本+渠道名+编译平台
         *
         * @return apk唯一标示符
         */
        @Override
        public String getQualifier() {
            String qualifier = "";
            try {
                PackageInfo info = MyApplication.getAppContext().getPackageManager()
                        .getPackageInfo(MyApplication.getAppContext().getPackageName(), 0);
                qualifier += info.versionCode + "_" + info.versionName + "_YYB";
            } catch (PackageManager.NameNotFoundException e) {
                Log.e(TAG, "getQualifier exception", e);
            }
            return qualifier;
        }

        @Override
        public String getUid() {
            return "87224330";
        }

        @Override
        public String getNetworkType() {
            return "4G";
        }

        @Override
        public int getConfigDuration() {
            return 9999;
        }

        @Override
        public int getConfigBlockThreshold() {
            return 500;
        }

        /**
         * 是否开启通知
         *
         * @return
         */
        @Override
        public boolean isNeedDisplay() {

            return true;
        }
    }

**Comment by markzhai** [comment]
请检查下，是否制定了输出log的路径且有写权限，可能log文件没有写成功

**Comment by qq137712630** [comment]
可能是手机自身的问题，我把这``` /blockcanary/performance ```目录的log全删除后，又可以打开了
