### ISSUE TITLE
Android6.0权限问题

### ISSUE THREAD

**Issue by yangyonguo** [moduth/blockcanary#47]
您好，我在android6.0下集成Blockcanary，出现下面的错误，应该是Runtime Permission机制导致的（后来在系统设置里手工设置权限后重启应用没有再出现）。请教Blockcanary现在处理Runtime Permisssion是不是通过发送权限授权通知？

错误信息如下：
05-10 10:42:03.196 4973-5451/cn.com.panchan.homelauncher.debug E/LogWriter: saveLogToSDCard: 
                                                                            java.io.FileNotFoundException: /data/storage/emulated/0/Android/data/cn.com.example.homelauncher.debug/files/log/blockcanary/looper-2016-05-10_10-42-03.193.txt: open failed: ENOENT (No such file or directory)
                                                                                at libcore.io.IoBridge.open(IoBridge.java:459)
                                                                                at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
                                                                                at java.io.FileOutputStream.<init>(FileOutputStream.java:127)
                                                                                at com.github.moduth.blockcanary.LogWriter.saveLogToSDCard(LogWriter.java:105)
                                                                                at com.github.moduth.blockcanary.LogWriter.saveLooperLog(LogWriter.java:53)
                                                                                at com.github.moduth.blockcanary.BlockCanaryCore$1.onBlockEvent(BlockCanaryCore.java:60)
                                                                                at com.github.moduth.blockcanary.LooperPrinter$1.run(LooperPrinter.java:72)
                                                                                at android.os.Handler.handleCallback(Handler.java:743)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:150)
                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                             Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                                at libcore.io.Posix.open(Native Method)
                                                                                at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                                                at libcore.io.IoBridge.open(IoBridge.java:445)
                                                                                at java.io.FileOutputStream.<init>(FileOutputStream.java:87) 
                                                                                at java.io.FileOutputStream.<init>(FileOutputStream.java:127) 
                                                                                at com.github.moduth.blockcanary.LogWriter.saveLogToSDCard(LogWriter.java:105) 
                                                                                at com.github.moduth.blockcanary.LogWriter.saveLooperLog(LogWriter.java:53) 
                                                                                at com.github.moduth.blockcanary.BlockCanaryCore$1.onBlockEvent(BlockCanaryCore.java:60) 
                                                                                at com.github.moduth.blockcanary.LooperPrinter$1.run(LooperPrinter.java:72) 
                                                                                at android.os.Handler.handleCallback(Handler.java:743) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                at android.os.Looper.loop(Looper.java:150) 
                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by markzhai** [comment]
你好，现在没有做任何权限适配哦，是直接manifest写的
